#Mapa {#Mapa}
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Hexabin XY scatter plot and transparent point XY plot R Markdown

```{r eval=FALSE, include=FALSE}
# data
library(OpenStreetMap)
library(rgdal)

# get world map
map <- openmap(c(70,-179), c(-70,179))
plot(map)

bingmap <- openmap(c(70,-179), c(-70,179), type = "bing")
plot(bingmap)
 #zoom maps, plot a portion
# upperLeft, lowerRight
lat <- c(43.834526782236814, 30.334953881988564)
lon <- c(-85.8857421875, -70.0888671875)
southest <- openmap(c(lat[1],lon[1]),c(lat[2],lon[2]),zoom=7,'osm')
plot(southest) 

require(maps)


library(mapproj)



worldmap <- map('world', plot = FALSE, fill = FALSE,  projection = "azequalarea")


country = worldmap$names


set.seed(1234)


var.2010 = rnorm (length (country), 20, 10)


var.2011 = var.2010*1.1 + rnorm (length (country), 0, 1)


var.2012 = var.2011*0.98 + rnorm (length (country), 0, 4)


var.2013 = var.2011*0.98 + rnorm (length (country), 0, 30)


worldt <- data.frame (country, var.2010, var.2011, var.2012, var.2013)


library(oce)
mapPlot(country ~ var.2011, worldt, map = map("world",     plot = FALSE, fill = TRUE))
mapPlot(country ~ var.2010 + var.2011 + var.2012 + var.2013, data = worldt, map = map("world",     plot = FALSE, fill = TRUE))
```

