---
title: "Gráfico de Barras"
author: "DATAUNIRIO"
output: 
   html_document:
     theme: flatly
     highlight: tango
---
<head>
<style>
body {
    background-color:#fdf6e3;
}
</style>
</head>


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
require(RcmdrMisc)
```

Clique [aqui](https://dataunirio.github.io/GALERIA_DE_GRAFICOS/) para voltar a página principal.

```{r barras, message=FALSE, warning=FALSE}
data(mtcars)
mtcars <- within(mtcars, {
  am <- factor(am, labels=c('Automático','Manual'))
})
mtcars <- within(mtcars, {
  vs <- factor(vs, labels=c('Não','Sim'))
})
par(bg="#fdf6e3") 

contagem = table(mtcars$am)
nomes = levels(mtcars$am)
porcent = round(prop.table(contagem)*100,2)
rotulo=paste(nomes," (",porcent,"%",")",sep="")
barras<-barplot(table(mtcars$am), ylab="Frequência", main="Tipo de marcha", col=c("red","blue"))
text(barras, 0, rotulo,cex=1,pos=3,col ="#ffffff")

contagem2 = table(mtcars$vs)
nomes2 = levels(mtcars$vs)
porcent2 = round(prop.table(contagem2)*100,2)
rotulo2=paste(nomes2," (",porcent2,"%",")",sep="")
barras2<-barplot(table(mtcars$vs), ylab="Frequência", main="Tipo", col=c("#003154","#dd4a37"))
text(barras2, 0, rotulo,cex=1,pos=3,col ="#ffffff")
```

```{r barras2, message=FALSE, warning=FALSE}
par(bg="#fdf6e3") 
library(plotrix)
barpos<-barplot(contagem,main="Gráfico de Barras",col=c("red","blue"))
barlabels(barpos,contagem,col=c("red","blue"))

barpos2<-barplot(contagem2,main="Gráfico de Barras", col=c("#003154","#dd4a37"))
barlabels(barpos2,contagem2,cex=1.3,prop=0.1, col=c("#003154","#dd4a37"))

```

# Gráficos de Barras "GAP"
```{r barrasGAP, message=FALSE, warning=FALSE}
library(RColorBrewer)
par(bg="#fdf6e3") 
#display.brewer.all()
COR<-brewer.pal(4,"Dark2")
#COR

library(plotrix)
twogrp<-c(rnorm(10)+4,rnorm(10)+20)
 gap.barplot(twogrp,gap=c(8,16),xlab="Index",ytics=c(3,6,17,20),
  ylab="Group values",main="Gráfico de Barras com um'GAP'")
gap.barplot(twogrp,gap=c(8,16),xlab="Index",ytics=c(3,6,17,20),
  ylab="Valores",horiz=TRUE,main="Gráfico de Barras com um'GAP'")

```

# Barras no ggplot2

```{r barrasggplot}
library(ggplot2)
ggplot(data=mtcars, aes(x=am)) +
  geom_bar(stat="count", fill="steelblue")+
  theme_minimal()
```

# Rótulos das Barras no ggplot2

```{r barrasggplot2, message=FALSE, warning=FALSE}

dados = data.frame(round(prop.table(contagem)*100,2))
dados <- within(dados, {
  Var1 <- factor(Var1, labels=c('Automático','Manual'))
})
attach(dados)
dados <- dados[order(Freq),] 
detach(dados)


# Fora das Barras
ggplot(data=dados, aes(x=Var1, y=Freq)) +
  geom_bar(stat="identity", fill="steelblue")+
  geom_text(aes(label=Freq), vjust=-0.3, size=3.5)+
  theme_minimal()
# Dentro das Barras
ggplot(data=dados, aes(x=Var1, y=Freq)) +
  geom_bar(stat="identity", fill="#275b70")+
  geom_text(aes(label=Freq), vjust=1.6, color="white",size=3.5)+
  theme_minimal()

```

# Alternativas ao Gráfico de Barras

## Gráficos "Dotplot" para variáveis discretas.
```{r dotplot, message=FALSE, warning=FALSE}
library(plotrix)  
x <- rpois(100,10)
dotplot.mtb(x,yaxis=TRUE,main="Dotplot")

set.seed(1001)
bvals <- matrix(rpois(12,20),nrow=3)
b <- symbolbarplot(bvals)
```

Clique [aqui](https://dataunirio.github.io/GALERIA_DE_GRAFICOS/) para voltar a página principal.